# -*- coding: utf-8 -*-
"""Task_1_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxQD3mqqiR4qlrGaYM_ik9jjLKq0NJ0W
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import transforms
from medmnist import PneumoniaMNIST
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import seaborn as sns

# Define transforms
transform = transforms.Compose([
    transforms.ToTensor()
])

# Load the training set
train_dataset = PneumoniaMNIST(split='train', transform=transform, download=True)

print("Number of training samples:", len(train_dataset))
sample_img, sample_label = train_dataset[102]
print("Sample image shape:", sample_img.shape)  # Usually (1, 28, 28) for grayscale images
print("Sample label:", sample_label)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from collections import Counter

transform = transforms.Compose([transforms.ToTensor()])

train_dataset = PneumoniaMNIST(split='train', transform=transform, download=True)
val_dataset   = PneumoniaMNIST(split='val', transform=transform, download=True)
test_dataset  = PneumoniaMNIST(split='test', transform=transform, download=True)

#   Split
print(f"Training set size: {len(train_dataset)}")
print(f"Validation set size: {len(val_dataset)}")
print(f"Test set size: {len(test_dataset)}")

def count_labels(dataset):
    labels = [int(label) for _, label in dataset]
    counter = Counter(labels)
    print(f"Label counts: {counter}")
    print(f"Normal: {counter.get(0,0)}, Pneumonia: {counter.get(1,0)}\n")
    return labels

print("Training set labels:")
train_labels = count_labels(train_dataset)

print("Validation set labels:")
val_labels = count_labels(val_dataset)

print("Test set labels:")
test_labels = count_labels(test_dataset)

# 3) Visualization Example

plt.figure(figsize=(6,6))
for i in range(9):
    image, label = train_dataset[i]
    plt.subplot(3,3,i+1)
    plt.imshow(image.squeeze(), cmap='gray')
    plt.title("Pneumonia" if label==1 else "Normal")
    plt.axis('off')
plt.show()

# 2) Data Preprocessing

# Augmentation + Normalization
transform_train = transforms.Compose([
    transforms.RandomRotation(10),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# 3) Load Dataset
train_dataset = PneumoniaMNIST(split='train', transform=transform_train, download=True)
val_dataset   = PneumoniaMNIST(split='val',   transform=transform_test, download=True)
test_dataset  = PneumoniaMNIST(split='test',  transform=transform_test, download=True)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=128)
test_loader  = DataLoader(test_dataset, batch_size=128)